name: Publish

on:
  push:
    branches:
      - actions
    tags:
      - "v*"

jobs:
  build:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Vayesta along with dependencies
        run: |
          python -m pip install wheel --user
          python -m pip install setuptools --upgrade --user
          python -m pip install . --user
      #- name: Run unit tests
      #  run: |
      #    python -m pip install pytest pytest-cov --user
      #    python .github/workflows/run_tests.py
      - name: Packaging
        run: |
          python setup.py sdist
      - name: Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
